# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1925f95788e45d17bb530fbda0372f77aefa4b3c0905b7fee3a81e0b0b339da374bc7bb9f9bc6fec974fd7426fe5398403a770b688aa083abb1e8aaa6c550b37

test:
  secret_key_base: 723eaf9f7718236fa429c48aa587ccedaf75135c681b449452dbe3268c2113685ae26f5d2811a3bc2833108d91b10c60ae10dfbe20899cffc3e75dd1ea6aee1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
